image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test
  - deploy

before_script:
    - "dotnet restore" 

build:
  stage: build
  script:
     - "dotnet build"

test:
  stage: test
  script:
    - "cd CIMS-Tests"
    - "dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover"
    - "dotnet msbuild -target:Coverage"
    - "ls"
  artifacts:
    paths:
      - CIMS-Tests/report/
      
pages:
  stage: deploy
  dependencies:
    - test
  script:
    - "ls CIMS-Tests"
    - "mv CIMS-Tests/report/ public/"
  artifacts:
    paths:
      - public
  only:
    - Development
