version: '3.2'

services:
    database:
        image: mysql:latest
        container_name: userdb
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pew
            MYSQL_DATABASE: userdb
        ports:
            - "3306:3306"