apiVersion: v1
kind: Service
metadata:
    name: "gridnorthcluster-47d1"
    labels:
        app: "gridnorthcluster-47d1"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "gridnorthcluster-47d1"