package proftaak.service.marketservice.model;

public enum TransactionType {
    BALANCERESPONSE,
    BUYOFFERREQUEST,
    BUYOFFERRESPONSE,
    CREATEACCOUNTREQUEST,
    CREATESELLOFFERREQUEST,
    LOGINACCOUNTREQUEST,
    OFFERRESPONSE
}