server:
  port: 8091

spring:
  application:
    name: gas-service
  rabbitmq:
    dynamic: true
    host: host.docker.internal
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    preferIpAddress: true
    hostname: host.docker.internal
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8083/eureka
    healthcheck:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric