#Specify which branch
trigger:
- master

pool:
  vmImage: ubuntu-latest

#Stage 1: Build Maven and run tests
stages:
- stage: BuildAndTest
  displayName: Maven Tests & Create Docker Image
  jobs:
  - job: BuildAndTest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean package'
    - task: DockerInstaller@0
      displayName: Install Docker
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: Docker@2
      displayName: Docker BuildAndPush
      inputs:
        containerRegistry: 'Songify'
        repository: 's631egn/oilsimulation.service'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: DockerCompose@0
      displayName: DockerCompose - Push
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Songify'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
    - task: DockerCompose@0
      displayName: DockerCompose - Up
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Songify'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up'

#Stage 2: Push docker image into kubernetes cluster
- stage: k8sAndHelm
  displayName: k8s & Helm
  jobs:
  - job: Deployment
    steps:
    - task: HelmInstaller@0
      displayName: Install k8s & Helm
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true
    - task: HelmDeploy@0
      displayName: Deploy via Helm
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: 'KubeEGN'
        azureSubscriptionForACR: '$(azureSubscription)'
        azureResourceGroupForACR: 'songify'
        azureContainerRegistry: 'Songify'
        command: 'ls'
