server:
  port: 8899

spring:
  application:
    name: invoice-service
  rabbitmq:
    dynamic: true
    host: host.docker.internal
    port: 5672
    username: guest
    password: guest
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://host.docker.internal:3308/invoicedb
    username: root
    password: my-secret-pew
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    preferIpAddress: true
    hostname: host.docker.internal
    nonSecurePortEnabled: true
    nonSecurePort: 8083
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka/
    healthcheck:
      enabled: true
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
