// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAnMa15V2VpwCgAqbKfoKfEPnWPlUfBD0',
    appId: '1:928962658328:web:53c351b26fb1e07248c36d',
    messagingSenderId: '928962658328',
    projectId: 'cimregistration',
    authDomain: 'cimregistration.firebaseapp.com',
    databaseURL: 'https://cimregistration-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cimregistration.appspot.com',
    measurementId: 'G-9J0BH6VWYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr90J4bBxkEddKZRXawfQ8dkkjYpMz6T8',
    appId: '1:928962658328:android:85cd4db9e970ec4948c36d',
    messagingSenderId: '928962658328',
    projectId: 'cimregistration',
    databaseURL: 'https://cimregistration-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cimregistration.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgbmxrmNPL5pWi9IQn4EqDQ3uQmK1gDB4',
    appId: '1:928962658328:ios:8cc64b740deb460b48c36d',
    messagingSenderId: '928962658328',
    projectId: 'cimregistration',
    databaseURL: 'https://cimregistration-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cimregistration.appspot.com',
    iosClientId: '928962658328-4vvc49g7sbjqr4cn6aqubvk7b6t8b8ec.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
